# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'invoice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinvoice.proto\"\x91\x01\n\x0fRechnungRequest\x12\x18\n\x10rechnungs_nummer\x18\x01 \x01(\t\x12\x11\n\tlieferant\x18\x02 \x01(\t\x12\x0e\n\x06\x62\x65trag\x18\x03 \x01(\x01\x12\x10\n\x08waehrung\x18\x04 \x01(\t\x12\r\n\x05\x64\x61tum\x18\x05 \x01(\t\x12 \n\x06status\x18\x06 \x01(\x0e\x32\x10.RechnungsStatus\"5\n\x10RechnungResponse\x12\x0e\n\x06\x65rfolg\x18\x01 \x01(\x08\x12\x11\n\tnachricht\x18\x02 \x01(\t*8\n\x0fRechnungsStatus\x12\t\n\x05OFFEN\x10\x00\x12\x0b\n\x07\x42\x45ZAHLT\x10\x01\x12\r\n\tABGELEHNT\x10\x02\x32L\n\x0fRechnungService\x12\x39\n\x12SpeichereMetadaten\x12\x10.RechnungRequest\x1a\x11.RechnungResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECHNUNGSSTATUS']._serialized_start=220
  _globals['_RECHNUNGSSTATUS']._serialized_end=276
  _globals['_RECHNUNGREQUEST']._serialized_start=18
  _globals['_RECHNUNGREQUEST']._serialized_end=163
  _globals['_RECHNUNGRESPONSE']._serialized_start=165
  _globals['_RECHNUNGRESPONSE']._serialized_end=218
  _globals['_RECHNUNGSERVICE']._serialized_start=278
  _globals['_RECHNUNGSERVICE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
